# Generated by Django 4.2 on 2023-07-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador_elecciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='loser',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userinput',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinput',
            name='round',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userinput',
            name='winner',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
