# Generated by Django 4.2 on 2023-07-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador_elecciones', '0002_userinput_loser_userinput_percentage_userinput_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
